import { useEffect, useState } from 'react';
import { NEWS_CATEGORIES, newsSeed, type NewsItem } from '../data/newsSeed';
import { InstagramStrip } from './InstagramStrip';

interface NewsFile {
  updated?: string;
  items?: NewsItem[];
}

export function News() {
  const [items, setItems] = useState<NewsItem[]>(newsSeed);
  const [usingSeed, setUsingSeed] = useState(true);
  const [updated, setUpdated] = useState<string | null>(null);
  const [filter, setFilter] = useState('all');

  // Headlines are generated by a scheduled GitHub Action into public/news.json —
  // no backend needed. Falls back to the built-in seed if the file isn't there yet.
  useEffect(() => {
    let active = true;
    fetch(`${import.meta.env.BASE_URL}news.json`, { cache: 'no-cache' })
      .then((r) => (r.ok ? (r.json() as Promise<NewsFile>) : null))
      .then((data) => {
        if (!active || !data) return;
        const arr = data.items ?? [];
        if (arr.length > 0) {
          setItems(arr);
          setUsingSeed(false);
          setUpdated(data.updated ?? null);
        }
      })
      .catch(() => {
        /* offline or not generated yet — keep the seed */
      });
    return () => {
      active = false;
    };
  }, []);

  const shown = filter === 'all' ? items : items.filter((i) => i.category === filter);

  return (
    <div className="view">
      <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 8 }}>Trek news</div>

      <InstagramStrip />

      {usingSeed ? (
        <div className="banner banner--info">
          Starter notes shown. Live Manaslu &amp; Nepal-trekking headlines update automatically
          every few hours.
        </div>
      ) : (
        updated && (
          <div className="small muted" style={{ margin: '0 2px 10px' }}>
            Auto-updated {new Date(updated).toLocaleString()} · headlines refresh every ~6 h
          </div>
        )
      )}

      <div className="chips">
        {NEWS_CATEGORIES.map((c) => (
          <button
            key={c}
            className={`chip${filter === c ? ' chip--active' : ''}`}
            onClick={() => setFilter(c)}
          >
            {c}
          </button>
        ))}
      </div>

      {shown.length === 0 && <div className="empty">No updates in this category yet.</div>}

      {shown.map((item) => (
        <div key={item.id} className="news">
          <div className="news__meta">
            <span className="badge">{item.category}</span>
            <span className="news__date">{item.date}</span>
          </div>
          <div className="news__title">{item.title}</div>
          {item.summary && <div className="news__summary">{item.summary}</div>}
          <div className="small muted" style={{ marginTop: 6, display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            {item.source && <span>— {item.source}</span>}
            {item.link && (
              <a href={item.link} target="_blank" rel="noreferrer noopener">
                Read more →
              </a>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}
