// AUTO-GENERATED by scripts/fetch-weather-snapshot.mjs — do not edit by hand.
// A real 7-day forecast baked in at build time, used ONLY as a last-resort
// fallback when the device has no live fetch and no cached forecast. Always
// shown with its capture date so it is never mistaken for current.

import type { PointWeather } from '../hooks/useWeather';

export const SNAPSHOT_AT = "2026-09-26T03:53:38.655Z";
export const weatherSnapshot: Record<string, PointWeather> = {
 "wp-kathmandu": {
  "current": {
   "temperature": 18.7,
   "code": 51,
   "wind": 8.9,
   "humidity": 92
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 55,
    "tmax": 21.3,
    "tmin": 16.3,
    "precip": 9.1,
    "precipProb": 99,
    "windMax": 10.5
   },
   {
    "date": "2026-09-27",
    "code": 80,
    "tmax": 22.7,
    "tmin": 17.8,
    "precip": 17.4,
    "precipProb": 100,
    "windMax": 12
   },
   {
    "date": "2026-09-28",
    "code": 96,
    "tmax": 26.4,
    "tmin": 17.2,
    "precip": 4,
    "precipProb": 99,
    "windMax": 6.5
   },
   {
    "date": "2026-09-29",
    "code": 95,
    "tmax": 26.1,
    "tmin": 15.9,
    "precip": 2.4,
    "precipProb": 98,
    "windMax": 5.1
   },
   {
    "date": "2026-09-30",
    "code": 51,
    "tmax": 25.8,
    "tmin": 15.7,
    "precip": 1.2,
    "precipProb": 92,
    "windMax": 5.1
   },
   {
    "date": "2026-10-01",
    "code": 95,
    "tmax": 23.7,
    "tmin": 17.4,
    "precip": 4.2,
    "precipProb": 99,
    "windMax": 7.6
   },
   {
    "date": "2026-10-02",
    "code": 51,
    "tmax": 24.8,
    "tmin": 17.8,
    "precip": 0.6,
    "precipProb": 84,
    "windMax": 6.8
   }
  ]
 },
 "wp-machhakhola": {
  "current": {
   "temperature": 23,
   "code": 51,
   "wind": 4.9,
   "humidity": 96
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 80,
    "tmax": 24.6,
    "tmin": 21.9,
    "precip": 29.9,
    "precipProb": 100,
    "windMax": 9.3
   },
   {
    "date": "2026-09-27",
    "code": 82,
    "tmax": 25.4,
    "tmin": 19.9,
    "precip": 60.1,
    "precipProb": 100,
    "windMax": 3.8
   },
   {
    "date": "2026-09-28",
    "code": 1,
    "tmax": 27.9,
    "tmin": 17.1,
    "precip": 0,
    "precipProb": 6,
    "windMax": 5.9
   },
   {
    "date": "2026-09-29",
    "code": 2,
    "tmax": 28.6,
    "tmin": 17.4,
    "precip": 0,
    "precipProb": 17,
    "windMax": 6.1
   },
   {
    "date": "2026-09-30",
    "code": 51,
    "tmax": 28.1,
    "tmin": 20.4,
    "precip": 0.3,
    "precipProb": 45,
    "windMax": 5.6
   },
   {
    "date": "2026-10-01",
    "code": 51,
    "tmax": 27.3,
    "tmin": 21.5,
    "precip": 0.9,
    "precipProb": 66,
    "windMax": 4.7
   },
   {
    "date": "2026-10-02",
    "code": 3,
    "tmax": 26.8,
    "tmin": 21.8,
    "precip": 0,
    "precipProb": 47,
    "windMax": 4.1
   }
  ]
 },
 "wp-jagat": {
  "current": {
   "temperature": 21.2,
   "code": 55,
   "wind": 1.1,
   "humidity": 92
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 81,
    "tmax": 22.2,
    "tmin": 18.9,
    "precip": 40.9,
    "precipProb": 100,
    "windMax": 5.1
   },
   {
    "date": "2026-09-27",
    "code": 81,
    "tmax": 24,
    "tmin": 15.5,
    "precip": 42.2,
    "precipProb": 99,
    "windMax": 6.9
   },
   {
    "date": "2026-09-28",
    "code": 1,
    "tmax": 28.4,
    "tmin": 14.5,
    "precip": 0,
    "precipProb": 4,
    "windMax": 8.5
   },
   {
    "date": "2026-09-29",
    "code": 51,
    "tmax": 28.5,
    "tmin": 15.3,
    "precip": 0.7,
    "precipProb": 13,
    "windMax": 8.8
   },
   {
    "date": "2026-09-30",
    "code": 51,
    "tmax": 28,
    "tmin": 17.8,
    "precip": 1.2,
    "precipProb": 47,
    "windMax": 8.3
   },
   {
    "date": "2026-10-01",
    "code": 51,
    "tmax": 27.1,
    "tmin": 18.7,
    "precip": 1.8,
    "precipProb": 71,
    "windMax": 7.7
   },
   {
    "date": "2026-10-02",
    "code": 53,
    "tmax": 26.1,
    "tmin": 20,
    "precip": 4.2,
    "precipProb": 63,
    "windMax": 7.6
   }
  ]
 },
 "wp-deng": {
  "current": {
   "temperature": 15.4,
   "code": 53,
   "wind": 1.9,
   "humidity": 97
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 80,
    "tmax": 17.1,
    "tmin": 13.9,
    "precip": 48,
    "precipProb": 100,
    "windMax": 4.9
   },
   {
    "date": "2026-09-27",
    "code": 63,
    "tmax": 16.6,
    "tmin": 10.8,
    "precip": 47.8,
    "precipProb": 100,
    "windMax": 6.9
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 26.8,
    "tmin": 8.2,
    "precip": 0,
    "precipProb": 6,
    "windMax": 8.3
   },
   {
    "date": "2026-09-29",
    "code": 51,
    "tmax": 27.4,
    "tmin": 8.3,
    "precip": 0.3,
    "precipProb": 2,
    "windMax": 7.4
   },
   {
    "date": "2026-09-30",
    "code": 51,
    "tmax": 27.2,
    "tmin": 10.8,
    "precip": 0.3,
    "precipProb": 4,
    "windMax": 4.7
   },
   {
    "date": "2026-10-01",
    "code": 51,
    "tmax": 26.8,
    "tmin": 11.3,
    "precip": 0.6,
    "precipProb": 6,
    "windMax": 5.2
   },
   {
    "date": "2026-10-02",
    "code": 51,
    "tmax": 26.9,
    "tmin": 13.4,
    "precip": 0.6,
    "precipProb": 14,
    "windMax": 4.7
   }
  ]
 },
 "wp-ghap": {
  "current": {
   "temperature": 13.5,
   "code": 53,
   "wind": 1.9,
   "humidity": 96
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 80,
    "tmax": 15.2,
    "tmin": 11.9,
    "precip": 48,
    "precipProb": 100,
    "windMax": 4.9
   },
   {
    "date": "2026-09-27",
    "code": 63,
    "tmax": 14.7,
    "tmin": 8.9,
    "precip": 47.8,
    "precipProb": 100,
    "windMax": 6.9
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 24.8,
    "tmin": 6.3,
    "precip": 0,
    "precipProb": 100,
    "windMax": 8.3
   },
   {
    "date": "2026-09-29",
    "code": 51,
    "tmax": 25.5,
    "tmin": 6.4,
    "precip": 0.3,
    "precipProb": 100,
    "windMax": 7.4
   },
   {
    "date": "2026-09-30",
    "code": 51,
    "tmax": 25.2,
    "tmin": 8.8,
    "precip": 0.3,
    "precipProb": 100,
    "windMax": 4.7
   },
   {
    "date": "2026-10-01",
    "code": 51,
    "tmax": 24.8,
    "tmin": 9.3,
    "precip": 0.6,
    "precipProb": 100,
    "windMax": 5.2
   },
   {
    "date": "2026-10-02",
    "code": 51,
    "tmax": 25,
    "tmin": 11.4,
    "precip": 0.6,
    "precipProb": 100,
    "windMax": 4.7
   }
  ]
 },
 "wp-namrung": {
  "current": {
   "temperature": 9.7,
   "code": 55,
   "wind": 2.9,
   "humidity": 98
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 80,
    "tmax": 11.3,
    "tmin": 8.5,
    "precip": 58,
    "precipProb": 100,
    "windMax": 5.1
   },
   {
    "date": "2026-09-27",
    "code": 71,
    "tmax": 10.7,
    "tmin": 5.8,
    "precip": 58.5,
    "precipProb": 100,
    "windMax": 6.2
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 20.4,
    "tmin": 2.1,
    "precip": 0,
    "precipProb": 100,
    "windMax": 7.4
   },
   {
    "date": "2026-09-29",
    "code": 1,
    "tmax": 21.4,
    "tmin": 2.7,
    "precip": 0,
    "precipProb": 100,
    "windMax": 6.9
   },
   {
    "date": "2026-09-30",
    "code": 1,
    "tmax": 21.4,
    "tmin": 4.7,
    "precip": 0,
    "precipProb": 100,
    "windMax": 4.9
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 21.5,
    "tmin": 4.9,
    "precip": 0,
    "precipProb": 100,
    "windMax": 4.7
   },
   {
    "date": "2026-10-02",
    "code": 2,
    "tmax": 21.6,
    "tmin": 6.3,
    "precip": 0,
    "precipProb": 100,
    "windMax": 3.3
   }
  ]
 },
 "wp-lihi": {
  "current": {
   "temperature": 7.8,
   "code": 55,
   "wind": 2.9,
   "humidity": 98
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 80,
    "tmax": 9.4,
    "tmin": 6.6,
    "precip": 58,
    "precipProb": 100,
    "windMax": 5.1
   },
   {
    "date": "2026-09-27",
    "code": 71,
    "tmax": 8.8,
    "tmin": 3.9,
    "precip": 58.5,
    "precipProb": 100,
    "windMax": 6.2
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 18.5,
    "tmin": 0.2,
    "precip": 0,
    "precipProb": 100,
    "windMax": 7.4
   },
   {
    "date": "2026-09-29",
    "code": 1,
    "tmax": 19.5,
    "tmin": 0.8,
    "precip": 0,
    "precipProb": 100,
    "windMax": 6.9
   },
   {
    "date": "2026-09-30",
    "code": 1,
    "tmax": 19.5,
    "tmin": 2.8,
    "precip": 0,
    "precipProb": 100,
    "windMax": 4.9
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 19.6,
    "tmin": 3,
    "precip": 0,
    "precipProb": 100,
    "windMax": 4.7
   },
   {
    "date": "2026-10-02",
    "code": 2,
    "tmax": 19.7,
    "tmin": 4.4,
    "precip": 0,
    "precipProb": 100,
    "windMax": 3.3
   }
  ]
 },
 "wp-lho": {
  "current": {
   "temperature": 7.2,
   "code": 61,
   "wind": 2.3,
   "humidity": 97
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 85,
    "tmax": 8.6,
    "tmin": 6.7,
    "precip": 70.6,
    "precipProb": 100,
    "windMax": 3.7
   },
   {
    "date": "2026-09-27",
    "code": 86,
    "tmax": 9,
    "tmin": 1.8,
    "precip": 85.3,
    "precipProb": 100,
    "windMax": 2.9
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 13.9,
    "tmin": -2.5,
    "precip": 0,
    "precipProb": 6,
    "windMax": 5.2
   },
   {
    "date": "2026-09-29",
    "code": 3,
    "tmax": 14.3,
    "tmin": -0.8,
    "precip": 0,
    "precipProb": 2,
    "windMax": 4.6
   },
   {
    "date": "2026-09-30",
    "code": 2,
    "tmax": 14.7,
    "tmin": -0.4,
    "precip": 0,
    "precipProb": 4,
    "windMax": 4.4
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 15,
    "tmin": 1.2,
    "precip": 0,
    "precipProb": 6,
    "windMax": 3.8
   },
   {
    "date": "2026-10-02",
    "code": 3,
    "tmax": 14.9,
    "tmin": 2.4,
    "precip": 0,
    "precipProb": 14,
    "windMax": 4.1
   }
  ]
 },
 "wp-shyala": {
  "current": {
   "temperature": 5.1,
   "code": 61,
   "wind": 2.3,
   "humidity": 97
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 85,
    "tmax": 6.5,
    "tmin": 4.6,
    "precip": 70.6,
    "precipProb": 100,
    "windMax": 3.7
   },
   {
    "date": "2026-09-27",
    "code": 86,
    "tmax": 6.9,
    "tmin": -0.3,
    "precip": 85.3,
    "precipProb": 100,
    "windMax": 2.9
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 11.8,
    "tmin": -4.6,
    "precip": 0,
    "precipProb": 6,
    "windMax": 5.2
   },
   {
    "date": "2026-09-29",
    "code": 3,
    "tmax": 12.2,
    "tmin": -2.9,
    "precip": 0,
    "precipProb": 2,
    "windMax": 4.6
   },
   {
    "date": "2026-09-30",
    "code": 2,
    "tmax": 12.6,
    "tmin": -2.5,
    "precip": 0,
    "precipProb": 4,
    "windMax": 4.4
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 12.9,
    "tmin": -0.9,
    "precip": 0,
    "precipProb": 6,
    "windMax": 3.8
   },
   {
    "date": "2026-10-02",
    "code": 3,
    "tmax": 12.8,
    "tmin": 0.3,
    "precip": 0,
    "precipProb": 14,
    "windMax": 4.1
   }
  ]
 },
 "wp-samagaon": {
  "current": {
   "temperature": 4.9,
   "code": 61,
   "wind": 2.3,
   "humidity": 97
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 85,
    "tmax": 6.3,
    "tmin": 4.4,
    "precip": 70.6,
    "precipProb": 100,
    "windMax": 3.7
   },
   {
    "date": "2026-09-27",
    "code": 86,
    "tmax": 6.7,
    "tmin": -0.5,
    "precip": 85.3,
    "precipProb": 100,
    "windMax": 2.9
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 11.6,
    "tmin": -4.8,
    "precip": 0,
    "precipProb": 6,
    "windMax": 5.2
   },
   {
    "date": "2026-09-29",
    "code": 3,
    "tmax": 12,
    "tmin": -3.1,
    "precip": 0,
    "precipProb": 2,
    "windMax": 4.6
   },
   {
    "date": "2026-09-30",
    "code": 2,
    "tmax": 12.4,
    "tmin": -2.7,
    "precip": 0,
    "precipProb": 4,
    "windMax": 4.4
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 12.7,
    "tmin": -1.1,
    "precip": 0,
    "precipProb": 6,
    "windMax": 3.8
   },
   {
    "date": "2026-10-02",
    "code": 3,
    "tmax": 12.6,
    "tmin": 0.1,
    "precip": 0,
    "precipProb": 14,
    "windMax": 4.1
   }
  ]
 },
 "wp-samdo": {
  "current": {
   "temperature": 3.5,
   "code": 73,
   "wind": 2.5,
   "humidity": 96
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 75,
    "tmax": 4.8,
    "tmin": 2.8,
    "precip": 74.7,
    "precipProb": 100,
    "windMax": 3.8
   },
   {
    "date": "2026-09-27",
    "code": 75,
    "tmax": 4.3,
    "tmin": -2.6,
    "precip": 84.3,
    "precipProb": 100,
    "windMax": 3.2
   },
   {
    "date": "2026-09-28",
    "code": 2,
    "tmax": 9,
    "tmin": -7.6,
    "precip": 0,
    "precipProb": 0,
    "windMax": 4.4
   },
   {
    "date": "2026-09-29",
    "code": 2,
    "tmax": 9.5,
    "tmin": -6.8,
    "precip": 0,
    "precipProb": 0,
    "windMax": 4
   },
   {
    "date": "2026-09-30",
    "code": 2,
    "tmax": 10,
    "tmin": -6.3,
    "precip": 0,
    "precipProb": 0,
    "windMax": 3.1
   },
   {
    "date": "2026-10-01",
    "code": 0,
    "tmax": 10.2,
    "tmin": -5.1,
    "precip": 0,
    "precipProb": 0,
    "windMax": 2.7
   },
   {
    "date": "2026-10-02",
    "code": 3,
    "tmax": 9.7,
    "tmin": -4.7,
    "precip": 0,
    "precipProb": 0,
    "windMax": 3.4
   }
  ]
 },
 "wp-dharamsala": {
  "current": {
   "temperature": 2.8,
   "code": 75,
   "wind": 1.7,
   "humidity": 94
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 75,
    "tmax": 2.8,
    "tmin": 1.5,
    "precip": 77,
    "precipProb": 100,
    "windMax": 3.3
   },
   {
    "date": "2026-09-27",
    "code": 86,
    "tmax": 2.9,
    "tmin": -6,
    "precip": 66.1,
    "precipProb": 100,
    "windMax": 2.4
   },
   {
    "date": "2026-09-28",
    "code": 3,
    "tmax": 4.4,
    "tmin": -9.2,
    "precip": 0,
    "precipProb": 10,
    "windMax": 3
   },
   {
    "date": "2026-09-29",
    "code": 0,
    "tmax": 5.1,
    "tmin": -8.9,
    "precip": 0,
    "precipProb": 10,
    "windMax": 3
   },
   {
    "date": "2026-09-30",
    "code": 0,
    "tmax": 5.5,
    "tmin": -8.2,
    "precip": 0,
    "precipProb": 8,
    "windMax": 1.9
   },
   {
    "date": "2026-10-01",
    "code": 0,
    "tmax": 5.7,
    "tmin": -6.8,
    "precip": 0,
    "precipProb": 16,
    "windMax": 2.5
   },
   {
    "date": "2026-10-02",
    "code": 0,
    "tmax": 5.8,
    "tmin": -6.9,
    "precip": 0,
    "precipProb": 16,
    "windMax": 1.7
   }
  ]
 },
 "wp-larkela": {
  "current": {
   "temperature": -2.3,
   "code": 75,
   "wind": 1.5,
   "humidity": 95
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 75,
    "tmax": -2.2,
    "tmin": -3.5,
    "precip": 74.1,
    "precipProb": 100,
    "windMax": 3.4
   },
   {
    "date": "2026-09-27",
    "code": 75,
    "tmax": -1.3,
    "tmin": -9.7,
    "precip": 58.1,
    "precipProb": 100,
    "windMax": 4.5
   },
   {
    "date": "2026-09-28",
    "code": 2,
    "tmax": -0.3,
    "tmin": -12.1,
    "precip": 0,
    "precipProb": 0,
    "windMax": 3.5
   },
   {
    "date": "2026-09-29",
    "code": 1,
    "tmax": 0.9,
    "tmin": -11,
    "precip": 0,
    "precipProb": 0,
    "windMax": 3.5
   },
   {
    "date": "2026-09-30",
    "code": 1,
    "tmax": 1.5,
    "tmin": -9.3,
    "precip": 0,
    "precipProb": 0,
    "windMax": 3
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 1.6,
    "tmin": -8.4,
    "precip": 0,
    "precipProb": 2,
    "windMax": 3.2
   },
   {
    "date": "2026-10-02",
    "code": 0,
    "tmax": 1.9,
    "tmin": -8.8,
    "precip": 0,
    "precipProb": 0,
    "windMax": 2.7
   }
  ]
 },
 "wp-bimthang": {
  "current": {
   "temperature": 4.5,
   "code": 61,
   "wind": 1,
   "humidity": 90
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 75,
    "tmax": 4.7,
    "tmin": 2.7,
    "precip": 65.4,
    "precipProb": 100,
    "windMax": 3
   },
   {
    "date": "2026-09-27",
    "code": 75,
    "tmax": 6.8,
    "tmin": -4.2,
    "precip": 60.4,
    "precipProb": 100,
    "windMax": 3.8
   },
   {
    "date": "2026-09-28",
    "code": 1,
    "tmax": 10.2,
    "tmin": -7,
    "precip": 0,
    "precipProb": 10,
    "windMax": 4.5
   },
   {
    "date": "2026-09-29",
    "code": 1,
    "tmax": 10.8,
    "tmin": -4.6,
    "precip": 0,
    "precipProb": 10,
    "windMax": 4.7
   },
   {
    "date": "2026-09-30",
    "code": 1,
    "tmax": 10.7,
    "tmin": -5.5,
    "precip": 0,
    "precipProb": 8,
    "windMax": 3.6
   },
   {
    "date": "2026-10-01",
    "code": 1,
    "tmax": 10.8,
    "tmin": -4.1,
    "precip": 0,
    "precipProb": 16,
    "windMax": 3.5
   },
   {
    "date": "2026-10-02",
    "code": 0,
    "tmax": 13.8,
    "tmin": -1.7,
    "precip": 0,
    "precipProb": 16,
    "windMax": 4.9
   }
  ]
 },
 "wp-dharapani": {
  "current": {
   "temperature": 15.9,
   "code": 80,
   "wind": 3.9,
   "humidity": 89
  },
  "daily": [
   {
    "date": "2026-09-26",
    "code": 81,
    "tmax": 17.1,
    "tmin": 14.1,
    "precip": 59.2,
    "precipProb": 100,
    "windMax": 10.4
   },
   {
    "date": "2026-09-27",
    "code": 82,
    "tmax": 22.4,
    "tmin": 7.3,
    "precip": 67.8,
    "precipProb": 100,
    "windMax": 8.3
   },
   {
    "date": "2026-09-28",
    "code": 1,
    "tmax": 25,
    "tmin": 6.8,
    "precip": 0,
    "precipProb": 14,
    "windMax": 9.6
   },
   {
    "date": "2026-09-29",
    "code": 51,
    "tmax": 25.1,
    "tmin": 9.2,
    "precip": 0.2,
    "precipProb": 14,
    "windMax": 7.6
   },
   {
    "date": "2026-09-30",
    "code": 51,
    "tmax": 24.9,
    "tmin": 8.3,
    "precip": 0.6,
    "precipProb": 14,
    "windMax": 7.6
   },
   {
    "date": "2026-10-01",
    "code": 51,
    "tmax": 24,
    "tmin": 10,
    "precip": 0.9,
    "precipProb": 33,
    "windMax": 6.6
   },
   {
    "date": "2026-10-02",
    "code": 51,
    "tmax": 24,
    "tmin": 8.6,
    "precip": 0.6,
    "precipProb": 39,
    "windMax": 6.7
   }
  ]
 }
};
